# Stubs for requests (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .__version__ import __author__, __author_email__, __build__, __cake__, __copyright__, __description__, __license__, __title__, __url__, __version__
from .api import delete, get, head, options, patch, post, put, request
from .exceptions import ConnectTimeout, ConnectionError, FileModeWarning, HTTPError, ReadTimeout, RequestException, RequestsDependencyWarning, Timeout, TooManyRedirects, URLRequired
from .models import PreparedRequest, Request, Response
from .sessions import Session, session
from .status_codes import codes
from typing import Any

def check_compatibility(urllib3_version: Any, chardet_version: Any) -> None: ...
