# Stubs for requests.__version__ (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

__title__: str
__description__: str
__url__: str
__build__: int
__author_email__: str
__license__: str
__copyright__: str
__cake__: str
