# Stubs for requests._internal_utils (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .compat import builtin_str, is_py2, str
from typing import Any

def to_native_string(string: Any, encoding: str = ...): ...
def unicode_is_ascii(u_string: Any): ...
