# Stubs for requests.compat (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

is_py2: Any
is_py3: Any
builtin_str = str
bytes = str
str = unicode
basestring = basestring
numeric_types: Any
integer_types: Any
builtin_str = str
str = str
bytes = bytes
