# Stubs for requests.help (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

OpenSSL: Any
cryptography: Any

def info(): ...
def main() -> None: ...
