# Stubs for requests.hooks (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

HOOKS: Any

def default_hooks(): ...
def dispatch_hook(key: Any, hooks: Any, hook_data: Any, **kwargs: Any): ...
